name: ml-scoring-and-monitoring
channels:
  - defaults
dependencies:
  - python=3.10.4
  - pip=22.1.2
  - click=8.0.4
  - cycler=0.11.0ml-scoring-monitoring
  - Flask=2.1.3
  # - gunicorn=20.1.0
  - joblib=1.1.0
  - kiwisolver=1.4.2
  - matplotlib=3.5.2
  - Pillow=9.2.0
  - pytz=2022.1
  - scikit-learn=1.1.1
  - scipy=1.7.3
  # - seaborn=0.11.2
  - pandas=1.4.3
  - requests=2.28.1
  - ipython=8.4.0
